<#
You thank the cephalopods for the help and exit the trash compactor, finding
yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching
teleportation; you can't help but try it for yourself and step onto the large
yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the
only way out is the teleporter. Unfortunately, the teleporter seems to be
leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and
diagnostic equipment lying around. After connecting one of the diagnostic tools,
it helpfully displays error code 0H-N0, which apparently means that there's an
issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A
tachyon beam enters the manifold at the location marked S; tachyon beams always
move downward. Tachyon beams pass freely through empty space (.). However, if a
tachyon beam encounters a splitter (^), the beam is stopped; instead, a new
tachyon beam continues from the immediate left and from the immediate right of
the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

In this example, the incoming tachyon beam (|) extends downward from S until it
reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At that point, the original beam stops, and two new beams are emitted from the
splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At this point, the two splitters create a total of only three tachyon beams,
since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

This process continues until all of the tachyon beams reach a splitter or exit
the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|

To repair the teleporter, you first need to understand the beam-splitting
properties of the tachyon manifold. In this example, a tachyon beam is split a
total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
#>

function PrintGrid([char[,]] $grid) {
    for ($y = 0; $y -lt $grid.GetLength(1); $y++) {
        $line = ""
        for ($x = 0; $x -lt $grid.GetLength(0); $x++) {
            $line += $grid[$x,$y]
        }
        Write-Output $line
    }
}

$rawInput = Get-Content "$PSScriptRoot\input.txt"

$grid = [char[,]]::new($rawInput[0].Length, $rawInput.Length)

# Read the text into the grid
for ($y = 0; $y -lt $rawInput.Length; $y++) {
    for ($x = 0; $x -lt $rawInput[$y].Length; $x++) {
        $grid[$x,$y] = $rawInput[$y][$x]
    }
}

# Line by line. Then character by character.
# - If the current character is S, replace with a beam (|)
# - If the current character is a splitter (^), If the character above is a
#   beam (|), place a beam either side of the splitter. Increase split count.
# - If the current character is ., If the character above is a beam (|),
#   replace with a beam (|).
$splitCount = 0
for ($y = 0; $y -lt $grid.GetLength(1); $y++) {
    for ($x = 0; $x -lt $grid.GetLength(0); $x++) {
        switch ($grid[$x,$y]) {
            'S' {
                $grid[$x,$y] = '|'
            }
            '^' {
                if ($y -gt 0 -and $grid[$x,($y-1)] -eq '|') {
                    if ($x -gt 0) {
                        $grid[($x-1),$y] = '|'
                    }
                    if ($x -lt $grid.GetLength(0) - 1) {
                        $grid[($x+1),$y] = '|'
                    }
                    $splitCount++
                }
            }
            '.' {
                if ($y -gt 0 -and $grid[$x,($y-1)] -eq '|') {
                    $grid[$x,$y] = '|'
                }
            }
        }
    }
}

$splitCount